import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layout/page";



export const metadata: Metadata = {
  title: "Solverines",
  description: "Generated by Solverines",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout/>
        {children}
      </body>
    </html>
  );
}
